#!/usr/bin/env bash
# source-config.sh — Config resolver for OpenClaw scripts.
# Sources stack.env (generated by pre-deploy) for all config variables.
# Auto-detects local (dev machine) vs VPS context.
#
# Exports ENV__* vars (from .env), STACK__* vars (from stack.yml).
# Also exports: OPENCLAW_CONTEXT ("local"|"vps"), REPO_ROOT (local only)

_SC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
_STACK_ENV=""
_SEARCH="$_SC_DIR"
_DEPTH=0

while [ "$_SEARCH" != "/" ] && [ "$_DEPTH" -lt 10 ]; do
  if [ -f "$_SEARCH/.env" ] && [ -d "$_SEARCH/.deploy" ]; then
    # Local repo root — stack.env is in .deploy/
    OPENCLAW_CONTEXT="local"
    REPO_ROOT="$_SEARCH"
    _STACK_ENV="$_SEARCH/.deploy/stack.env"
    break
  fi
  if [ -f "$_SEARCH/stack.env" ] && [ -f "$_SEARCH/stack.json" ]; then
    # VPS deploy directory — stack.env is here
    OPENCLAW_CONTEXT="vps"
    REPO_ROOT=""
    _STACK_ENV="$_SEARCH/stack.env"
    break
  fi
  _SEARCH="$(cd "$_SEARCH/.." && pwd)"
  _DEPTH=$((_DEPTH + 1))
done

# Auto-run pre-deploy if stack.env missing or --force requested (local only)
if [ "$OPENCLAW_CONTEXT" = "local" ]; then
  _FORCE="${1:-}"
  if [ ! -f "$_STACK_ENV" ] || [ "$_FORCE" = "--force" ]; then
    echo "→ Running pre-deploy to generate stack.env..." >&2
    (cd "$REPO_ROOT" && npm run pre-deploy) >&2
  fi
fi

if [ -z "$_STACK_ENV" ] || [ ! -f "$_STACK_ENV" ]; then
  echo "Error: stack.env not found (searched up from $_SC_DIR)" >&2
  echo "Run 'npm run pre-deploy' to generate it." >&2
  return 1 2>/dev/null || exit 1
fi

set -a
# shellcheck disable=SC1090
source "$_STACK_ENV"
set +a

# Source .env for direct access to raw vars (local-only — includes auto-generated secrets)
if [ "$OPENCLAW_CONTEXT" = "local" ]; then
  set -a
  # shellcheck disable=SC1090
  source "${REPO_ROOT}/.env"
  set +a
fi

export OPENCLAW_CONTEXT REPO_ROOT

# Clean up internal variables
unset _SC_DIR _STACK_ENV _SEARCH _DEPTH _FORCE
