#!/usr/bin/env bash
# source-config.sh — Config resolver for OpenClaw scripts.
# Sources stack.env (generated by pre-deploy) for all config variables.
# Auto-detects local (dev machine) vs VPS context.
#
# Exports ENV__* vars (from .env) and STACK__* vars (from stack.yml).
# Also exports: OPENCLAW_CONTEXT ("local"|"vps"), REPO_ROOT (local only)

_SC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
_STACK_ENV=""
_SEARCH="$_SC_DIR"
_DEPTH=0

while [ "$_SEARCH" != "/" ] && [ "$_DEPTH" -lt 10 ]; do
  if [ -f "$_SEARCH/.env" ] && [ -d "$_SEARCH/.deploy" ]; then
    # Local repo root — stack.env is in .deploy/
    OPENCLAW_CONTEXT="local"
    REPO_ROOT="$_SEARCH"
    _STACK_ENV="$_SEARCH/.deploy/stack.env"
    break
  fi
  if [ -f "$_SEARCH/stack.env" ] && [ -f "$_SEARCH/stack.json" ]; then
    # VPS deploy directory — stack.env is here
    OPENCLAW_CONTEXT="vps"
    REPO_ROOT=""
    _STACK_ENV="$_SEARCH/stack.env"
    break
  fi
  _SEARCH="$(cd "$_SEARCH/.." && pwd)"
  _DEPTH=$((_DEPTH + 1))
done

if [ -z "$_STACK_ENV" ] || [ ! -f "$_STACK_ENV" ]; then
  echo "Error: stack.env not found (searched up from $_SC_DIR)" >&2
  echo "Run 'bun run pre-deploy' to generate it." >&2
  return 1 2>/dev/null || exit 1
fi

set -a
# shellcheck disable=SC1090
source "$_STACK_ENV"
set +a

export OPENCLAW_CONTEXT REPO_ROOT

# Clean up internal variables
unset _SC_DIR _STACK_ENV _SEARCH _DEPTH
